spring.application.name=identity
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/identity
spring.datasource.username=postgres
spring.datasource.password=270504
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

jwt.secret=change-this-secret-key-please-change-very-long
jwt.expiration-seconds=604800

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.sync-url=http://localhost:8082/api/ref-users/sync

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}

