spring.application.name=identity
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/identity
spring.datasource.username=postgres
spring.datasource.password=270504
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

jwt.secret=change-this-secret-key-please-change-very-long
jwt.expiration-seconds=604800

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/