server.port=8080

spring.application.name=api-gateway


spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# ROUTE 1: Cac API Cong khai cua Identity Service (Dang nhap / Dang ky)
spring.cloud.gateway.server.webflux.routes[0].id=identity-public-route
# lb:// nghia la Load Balancing, Gateway tu dong can bang tai neu chay nhieu cum Identity
spring.cloud.gateway.server.webflux.routes[0].uri=lb://identity
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/login, /api/auth/register

# ROUTE 2: Cac API Bao mat cua Identity Service (Can xac thuc va giai ma JWT)
spring.cloud.gateway.server.webflux.routes[1].id=identity-secured-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://identity
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/**

# =========================================================================
# CAU HINH DONG BO KHOA BI MAT JWT (KHOP 100% VOI IDENTITY SERVICE)
# =========================================================================
jwt.secret=change-this-secret-key-please-change-very-long

# =========================================================================
# CAU HINH DIA CHI TRO VE EUREKA SERVER TRUNG TAM
# =========================================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true