server.port=8080

spring.application.name=api-gateway


spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# ROUTE 1: Cac API cong khai cua management service
spring.cloud.gateway.server.webflux.routes[0].id=management-public-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://management
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/events/**

# ROUTE 2: Cac API cong khai cua Identity Service (Dang nhap / Dang ky)
spring.cloud.gateway.server.webflux.routes[1].id=identity-public-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://identity
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/login, /api/auth/register

# ROUTE 3: Cac API bao mat cua Identity Service (Can xac thuc va giai ma JWT)
spring.cloud.gateway.server.webflux.routes[2].id=identity-secured-route
spring.cloud.gateway.server.webflux.routes[2].uri=lb://identity
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/**



# CAU HINH DONG BO KHOA BI MAT JWT (KHOP 100% VOI IDENTITY SERVICE)
jwt.secret=change-this-secret-key-please-change-very-long
gateway.security.public-paths=/api/auth/login,/api/auth/register,/api/movies/**,/swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/api-docs/**,/actuator/health,/actuator/info

# CAU HINH DIA CHI TRO VE EUREKA SERVER TRUNG TAM
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true