spring.application.name=booking
server.port=8084
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=postgres
spring.datasource.password=270504
spring.datasource.driver-class-name=org.postgresql.Driver
# bật SQL logs tạm thời trong application.properties (thêm vào)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG
spring.devtools.restart.enabled=true
# chạy ứng dụng